In [1]:
import numpy as np
import cv2

In [2]:
from computeH import computeH
from utils import to_homogenous_coords

In [3]:
%load_ext autoreload
%autoreload 2

In [38]:
im1 = cv2.imread('crop1.jpg')
im2 = cv2.imread('crop2.jpg')

h1, w1, _ = im1.shape
h2, w2, _ = im2.shape

scale = max(h1, w1, h2, w2) / 2
t1_scale = max(h1, w1) / 2
t2_scale = max(h2, w2) / 2

In [39]:
#t1, t2 = get_correspondences(im1, im2)

t1 = np.load('cc1.npy')
t2 = np.load('cc2.npy')

t1 = t1.T
t2 = t2.T

In [56]:
# t1_scaled = t1 / np.array([[w1/2], [h1/2]])
# t2_scaled = t2 / np.array([[w2/2], [h2/2]])

# t1_scaled = t1 / scale
# t2_scaled = t2 / scale

t1_scaled = t1 / t1_scale
t2_scaled = t2 / t2_scale

In [57]:
H = computeH(t1_scaled, t2_scaled)

In [58]:
t1_hom = to_homogenous_coords(t1_scaled)

In [59]:
p_prime = np.matmul(H, t1_hom)

In [60]:
((p_prime / p_prime[2]) * t2_scale)[1]

array([139.01423494, 178.11736161, 216.22879774, 233.73285354,
       227.31363183, 240.04683989, 290.85364417, 405.06945867,
       384.10577465, 234.87070931, 230.00661652, 111.10793294])

In [61]:
t2[1]

array([139.21355932, 177.68813559, 216.12542373, 234.43728814,
       227.41355932, 239.36949153, 290.8779661 , 405.4       ,
       384.        , 234.4       , 230.2       , 111.34915254])

In [62]:
t2_prime = (p_prime[:2] / p_prime[2]) * t2_scale

In [63]:
np.sqrt(np.mean(np.square(t2_prime - t2)))

0.6352619713357522

In [79]:
t2_scaled

array([[0.46186321, 0.42194501, 0.40087707, 0.41362872, 0.35153374,
        0.37925471, 0.32048625, 0.36650307, 0.41972733, 0.32042718,
        0.31710066, 0.30933879],
       [0.30936347, 0.39486252, 0.48027872, 0.52097175, 0.50536347,
        0.5319322 , 0.64639548, 0.90088889, 0.85333333, 0.52088889,
        0.51155556, 0.24744256]])

In [78]:
t1_scaled

array([[0.28933623, 0.3797759 , 0.47364093, 0.53393405, 0.46792348,
        0.52509799, 0.62319785, 0.94282123, 0.92462935, 0.46643234,
        0.44979976, 0.06295586],
       [0.3070904 , 0.35603814, 0.39922316, 0.41176554, 0.42326271,
        0.4274435 , 0.48937853, 0.56583333, 0.535     , 0.43892655,
        0.43526836, 0.31648305]])

In [27]:
H[1][np.argmin(H[0])].reshape(3, 3)

array([[-5.69001535e-01, -8.22272338e-01, -2.37596945e-03],
       [ 4.94938711e-03, -6.80155845e-03,  4.23016998e-03],
       [-3.34028351e-03, -9.99176409e-07,  3.07071947e-05]])

In [24]:
H

(array([1.68890288e+11, 1.76125070e+09, 1.35054210e+06, 4.81905344e+04,
        9.69108160e+03, 6.55461979e+03, 2.44825535e+03, 5.80560487e-05,
        8.10315298e-03]),
 array([[ 1.09175241e-03,  3.03671955e-03, -6.86009897e-01,
          6.32950468e-01,  7.08007891e-02,  2.86018469e-03,
          3.51754015e-01, -1.16369524e-03, -7.34521204e-04],
        [ 8.22300907e-04,  4.88281145e-03, -5.12702730e-01,
         -1.52849538e-01, -4.75219845e-01, -3.08386194e-01,
         -6.26726926e-01,  4.24326584e-03,  2.79624844e-03],
        [ 3.81451986e-06,  3.00693442e-05, -2.34410566e-03,
         -2.76404403e-03, -3.78070933e-03,  1.09339052e-03,
         -2.41965493e-03, -9.89641571e-01, -1.43440134e-01],
        [ 1.94514795e-03,  1.02939155e-03,  4.04184555e-01,
          3.43839866e-01, -6.27076209e-01, -4.85139114e-01,
          2.99695680e-01, -5.98605076e-04, -1.32606341e-03],
        [ 1.38597878e-03,  4.06132686e-03,  3.21081669e-01,
          6.76028054e-01,  1.68569417e-01,  1.

In [17]:
np.argmin(H[0])

7

In [18]:
H[1][7]

array([-0.56201104, -0.00456939, -0.03986285, -0.20016311,  0.00822838,
        0.44956278,  0.42936653, -0.01919398,  0.50553928])

In [11]:
p_prime

array([[-0.36930601, -0.47163529, -0.5777355 , -0.64567876, -0.57163953,
        -0.63596243, -0.74708052, -1.10739559, -1.08652352, -0.57017885,
        -0.55143316, -0.11497864],
       [ 0.34133824,  0.30634494,  0.26983768,  0.24601134,  0.2727218 ,
         0.24993688,  0.2121986 ,  0.08613819,  0.09265737,  0.27370662,
         0.28027449,  0.43219682],
       [ 0.73626358,  0.81109977,  0.88921031,  0.94026152,  0.88291196,
         0.9317681 ,  1.01243218,  1.28248713,  1.26864617,  0.88072669,
         0.86665504,  0.54132073]])

In [77]:
(p_prime / p_prime[2])[:2]

array([[ 1.7709983 ,  0.50678909, -0.47664177, -1.0176289 , -0.42353794,
        -0.9222202 , -1.60678958, -3.47713375, -3.51307789, -0.4109301 ,
        -0.26627269,  4.67510481],
       [14.95548922, 15.28879206, 15.63545395, 15.99674879, 15.32136484,
        15.74308255, 15.83111725, 17.08781679, 17.31049341, 15.15107425,
        15.05206551, 12.15276685]])

In [78]:
t2_scaled

array([[1.31128357, 1.19795114, 1.1381368 , 1.17434022, 0.99804533,
        1.0767484 , 0.90989788, 1.04054499, 1.19165489, 0.90973015,
        0.90028578, 0.87824892],
       [0.61872693, 0.78972505, 0.96055744, 1.0419435 , 1.01072693,
        1.06386441, 1.29279096, 1.80177778, 1.70666667, 1.04177778,
        1.02311111, 0.49488512]])

In [18]:
b = np.array([[0]*8 + [1]]).reshape(-1, 1)

In [21]:
L = computeH(t1_scaled, t2_scaled)

In [22]:
new_h = np.linalg.lstsq(L, b)

LinAlgError: Incompatible dimensions

In [25]:
np.linalg.solve(L, b)

LinAlgError: Last 2 dimensions of the array must be square

In [24]:
b.shape

(9, 1)

In [62]:
np.zeros((L.shape[0], 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [29]:
t1_scaled

array([[0.57867246, 0.75955181, 0.94728187, 1.0678681 , 0.93584697,
        1.05019598, 1.24639571, 1.88564247, 1.84925869, 0.93286469,
        0.89959952, 0.12591172],
       [0.92415918, 1.07146273, 1.20142394, 1.23916901, 1.27376866,
        1.28635035, 1.4727379 , 1.70282132, 1.61003135, 1.3209075 ,
        1.30989852, 0.95242548]])

In [32]:
p_prime

array([[-0.36930601, -0.47163529, -0.5777355 , -0.64567876, -0.57163953,
        -0.63596243, -0.74708052, -1.10739559, -1.08652352, -0.57017885,
        -0.55143316, -0.11497864],
       [ 0.34133824,  0.30634494,  0.26983768,  0.24601134,  0.2727218 ,
         0.24993688,  0.2121986 ,  0.08613819,  0.09265737,  0.27370662,
         0.28027449,  0.43219682],
       [ 0.73626358,  0.81109977,  0.88921031,  0.94026152,  0.88291196,
         0.9317681 ,  1.01243218,  1.28248713,  1.26864617,  0.88072669,
         0.86665504,  0.54132073]])

In [17]:
h1, w1

(319, 480)

In [18]:
show(im1)

NameError: name 'show' is not defined

In [40]:
t1_scaled

array([[0.57867246, 0.75955181, 0.94728187, 1.0678681 , 0.93584697,
        1.05019598, 1.24639571, 1.88564247, 1.84925869, 0.93286469,
        0.89959952, 0.12591172],
       [0.92415918, 1.07146273, 1.20142394, 1.23916901, 1.27376866,
        1.28635035, 1.4727379 , 1.70282132, 1.61003135, 1.3209075 ,
        1.30989852, 0.95242548]])

In [41]:
t1_hom

array([[0.57867246, 0.75955181, 0.94728187, 1.0678681 , 0.93584697,
        1.05019598, 1.24639571, 1.88564247, 1.84925869, 0.93286469,
        0.89959952, 0.12591172],
       [0.92415918, 1.07146273, 1.20142394, 1.23916901, 1.27376866,
        1.28635035, 1.4727379 , 1.70282132, 1.61003135, 1.3209075 ,
        1.30989852, 0.95242548],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]])

In [42]:
t1

array([[138.88139059, 182.29243354, 227.34764826, 256.28834356,
        224.60327198, 252.04703476, 299.13496933, 452.55419223,
        443.82208589, 223.88752556, 215.90388548,  30.21881391],
       [147.40338983, 170.89830508, 191.62711864, 197.64745763,
        203.16610169, 205.17288136, 234.90169492, 271.6       ,
        256.8       , 210.68474576, 208.92881356, 151.91186441]])

In [43]:
t1_scaled

array([[0.57867246, 0.61418079, 0.75955181, 0.71207627, 0.94728187,
        0.79844633, 1.0678681 , 0.82353107, 0.93584697, 0.84652542,
        1.05019598, 0.85488701],
       [1.87545435, 1.4727379 , 2.83733036, 1.70282132, 2.78258361,
        1.61003135, 1.40368355, 1.3209075 , 1.35362938, 1.30989852,
        0.18945965, 0.95242548]])

In [44]:
t2_scaled

array([[0.86599352, 0.5800565 , 0.7911469 , 0.74036723, 0.75164451,
        0.9005226 , 0.77555385, 0.97682203, 0.65912577, 0.9475565 ,
        0.71110259, 0.99737288],
       [0.90419319, 1.82368631, 1.03402119, 2.54169279, 1.1841837 ,
        2.40752351, 0.90402651, 1.46959248, 0.89464136, 1.44326019,
        0.87274266, 0.69811381]])

In [47]:
t2

array([[207.83844581, 139.21355932, 189.87525562, 177.68813559,
        180.39468303, 216.12542373, 186.13292434, 234.43728814,
        158.19018405, 227.41355932, 170.66462168, 239.36949153],
       [144.21881391, 290.8779661 , 164.92638037, 405.4       ,
        188.87730061, 384.        , 144.19222904, 234.4       ,
        142.69529652, 230.2       , 139.20245399, 111.34915254]])

In [49]:
h, w

(319, 480)

In [19]:
t1 = np.load('cc1.npy')

In [21]:
t1.T

array([[138.88139059, 182.29243354, 227.34764826, 256.28834356,
        224.60327198, 252.04703476, 299.13496933, 452.55419223,
        443.82208589, 223.88752556, 215.90388548,  30.21881391],
       [147.40338983, 170.89830508, 191.62711864, 197.64745763,
        203.16610169, 205.17288136, 234.90169492, 271.6       ,
        256.8       , 210.68474576, 208.92881356, 151.91186441]])

In [54]:
h, status = cv2.findHomography(t1_scaled.T, t2_scaled.T, 0)

In [53]:
cv2.findHomography??

In [72]:
h / np.linalg.norm(h)

array([[ 0.20678362, -0.50058613,  0.73600227],
       [ 0.07504831,  0.24049283, -0.08012346],
       [-0.04400927,  0.02376217,  0.30424405]])

In [46]:
H

array([[-0.56201104, -0.00456939, -0.03986285],
       [-0.20016311,  0.00822838,  0.44956278],
       [ 0.42936653, -0.01919398,  0.50553928]])

In [71]:
new_h[3] / np.linalg.norm(new_h[3])

array([8.73585149e-01, 4.51065302e-01, 1.53537338e-01, 8.95844263e-02,
       3.11014039e-02, 2.15671092e-02, 1.87111929e-02, 2.70598701e-03,
       3.58464417e-04])

In [70]:
np.linalg.norm(new_h[3])

15.069929163410409

In [48]:
np.linalg.norm(H)

1.0000000000000189

In [50]:
np.matmul(h, t1_hom)

array([[1.2918609 , 1.17243301, 1.0861954 , 1.10604985, 0.95939156,
        1.01640922, 0.8430874 , 0.89899381, 1.0269365 , 0.87980501,
        0.87530945, 0.93762811],
       [0.60990044, 0.7709558 , 0.91999261, 0.97957377, 0.97435757,
        1.01250953, 1.20823834, 1.54779404, 1.46547242, 1.01088331,
        0.99397558, 0.5205607 ],
       [0.98847333, 0.97381367, 0.95680856, 0.9423136 , 0.96411293,
        0.94855486, 0.93473164, 0.86023388, 0.85824973, 0.96822597,
        0.97217799, 1.05617338]])

In [51]:
t2_scaled

array([[1.31128357, 1.19795114, 1.1381368 , 1.17434022, 0.99804533,
        1.0767484 , 0.90989788, 1.04054499, 1.19165489, 0.90973015,
        0.90028578, 0.87824892],
       [0.61872693, 0.78972505, 0.96055744, 1.0419435 , 1.01072693,
        1.06386441, 1.29279096, 1.80177778, 1.70666667, 1.04177778,
        1.02311111, 0.49488512]])

In [79]:
np.matmul((new_h[3] / np.linalg.norm(new_h[3])).reshape(3, 3), t1_hom)

array([[1.07591315, 1.30037017, 1.52298936, 1.64535719, 1.5456322 ,
        1.65120096, 1.90667108, 2.56889021, 2.49525154, 1.56428962,
        1.53026389, 0.69313804],
       [0.1021498 , 0.12293512, 0.14379478, 0.15577136, 0.14502042,
        0.15565562, 0.17902897, 0.24345144, 0.23730612, 0.14621933,
        0.1428969 , 0.06246861],
       [0.01368688, 0.01746995, 0.02133428, 0.02369273, 0.02131608,
        0.02348973, 0.02766522, 0.0402489 , 0.03931702, 0.02138783,
        0.02073561, 0.00529167]])

In [76]:
new_h[3].shape

(9,)

In [78]:
(new_h[3] / np.linalg.norm(new_h[3]))

array([8.73585149e-01, 4.51065302e-01, 1.53537338e-01, 8.95844263e-02,
       3.11014039e-02, 2.15671092e-02, 1.87111929e-02, 2.70598701e-03,
       3.58464417e-04])